export const LOGINBUYER = "LOGINBUYER";
export const LOGINSELLER = "LOGINSELLER";

export const SIGNUPBUYER = "SIGNUPBUYER";
export const SIGNUPSELLER = "SIGNUPSELLER";

export const GETBUYER = "GETBUYER";
export const UPDATEBUYER = "UPDATEBUYER";
export const DISMISSBUYERPROFILEALERT = "DISMISSBUYERPROFILEALERT";
export const UPDATEBUYERIMAGE = "UPDATEBUYERIMAGE"; 

export const GETSELLER = "GETSELLER";
export const UPDATESELLER = "UPDATESELLER";
export const DISMISSSELLERPROFILEALERT = "DISMISSSELLERPROFILEALERT";
export const UPDATESELLERIMAGE = "UPDATESELLERIMAGE"; 

export const STARTLOADER = "STARTLOADER";
export const STOPLOADER = "STOPLOADER";
export const SETMSG = "SETMSG";
export const CLRMSG = "CLRMSG";

export const GETSECTIONS = "GETSECTIONS";
export const GETITEMS = "GETITEMS";
export const RELOADMENU = "RELOADMENU";

export const SEARCHBYITEM = "SEARCHBYITEM";
export const SEARCHBYITEMFAILED = "SEARCHBYITEMFAILED";
export const SETCUISINES = "SETCUISINES";

export const SELECTRESTAURANT = "SELECTRESTAURANT";
export const SETCARTCOUNT = "SETCARTCOUNT";
export const ORDERSUCCESS = "ORDERSUCCESS";
export const CUSTOMERORDERS = "CUSTOMERORDERS";
export const RESTAURANTORDERS = "RESTAURANTORDERS";

export const LOGOUTSELLER = "LOGOUTSELLER";
export const LOGOUTBUYER = "LOGOUTBUYER";
export const CLEARSEARCH = "CLEARSEARCH";
export const SETAUTHBUYER = "SETAUTHBUYER";
export const SETAUTHSELLER = "SETAUTHSELLER";
export const SETUPORDERCHAT = "SETUPORDERCHAT";